name: Lint

on:
  push:
  pull_request:

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1

      - name: Install Python
        run: uv python install --python-preference only-managed 3.13

      - name: Install dependencies
        run: uv sync --group lint

      - name: Check formatting
        run: |
          precious tidy -a
          git diff --exit-code

      - name: Lint
        run: precious lint -a

      - name: Build
        run: ./build.sh

      - name: AppInspect
        run: precious lint --command appinspect geoip-1.0.0.tar.gz
